Add files via upload
LetaTreiden/java-filmorate pull request #1
Opened 2022-05-22 10:30 UTC by LetaTreiden

2022-05-22 12:25 UTC, LetaTreiden commented
Все проверила, в постмане работает как надо, но эти 6 тестов никак не могу пройти

2022-05-22 16:38 UTC, kukolev requested changes

2022-05-22 16:38 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Нарушение кодстайла: Лишние отступы перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-05-22 16:38 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private static final Logger logger = LoggerFactory.getLogger(Film.class);
Лучше использовать аннотацию @Slf4j, тогда логгер будет создавать автоматически фреймворком и не нужно будет писать однотипный код в каждом классе. Подробнее можно почитать тут: https://www.baeldung.com/slf4j-with-log4j2-logback

2022-05-22 16:38 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getName().isEmpty() || film.getName() == null) {
Здесь и ниже код валидации повторяется. Нужно вынести код в отдельный приватный метод, чтобы не дублировать.

2022-05-22 16:38 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (user.getEmail() == null || user.getEmail().isBlank() || !user.getEmail().contains("@")) {
Здесь и ниже код валидации повторяется. Нужно вынести код в отдельный приватный метод, чтобы не дублировать.

2022-05-22 16:38 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Объект LocalDate.of(1895, 12, 28) лучше сделать константой, чтобы не приходилось всякий раз создавать при валидации.

2022-05-23 15:05 UTC, kukolev approved these changes

2022-05-26 10:57 UTC, merged